### ISSUE TITLE
Using vint on own robot, at starting position the closest_node keeps changing even though the robot is at standstill 

### ISSUE THREAD

**Issue by vedant-banerjee** [robodhruv/visualnav-transformer#19]
The closest_node at starting point, keeps flickering between 0 and 5 , and when the controller is run, the robot navigates but the closest node detected seems to be wrong , hence the robot is unable to find the goal node and stop, any help on how to debug this issue will be appreciated, even the start and end values are changing even though the robot is at standstill.

**Comment by robodhruv** [comment]
Hi Vedant,

That is not expected behavior and we're happy to help debug. Would it be possible for you to share a few images from the start, or the entire topomap if possible? What camera are you using?

Dhruv

**Comment by vedant-banerjee** [comment]
Hi Dhruv ,
The current update is i have tried fine tuning the model by training it and the issue of finding the closest_node and goal node still seems to be an issue, also my robot is a much larger size compared to the locobot , and there are collisions taking place if obstacles are placed on the path. 
The camera i am using is Intel Realsense D435I , i have recorded a bag with a small path , which goes only straight and i am trying to use that.
I will share the images from the topomap along with my robot image.
![0](https://github.com/robodhruv/visualnav-transformer/assets/67970392/7aa7b23e-e7eb-4f47-98f5-31086974ff5b)
![1](https://github.com/robodhruv/visualnav-transformer/assets/67970392/2b132edd-fdb7-4f2c-a84f-6be88894405b)
![2](https://github.com/robodhruv/visualnav-transformer/assets/67970392/d09faaf4-895b-42a8-ae1a-a0d07128042f)
![3](https://github.com/robodhruv/visualnav-transformer/assets/67970392/5c01ff72-069d-4ac6-b91e-d32dbeb7ea60)
![4](https://github.com/robodhruv/visualnav-transformer/assets/67970392/79e2a573-72b1-4b19-9bde-6a7ce2a9ed90)
![5](https://github.com/robodhruv/visualnav-transformer/assets/67970392/fce246f7-6bd2-44bf-bfe5-99873ffe7958)
![6](https://github.com/robodhruv/visualnav-transformer/assets/67970392/52727461-437c-4d0f-88b1-fa7a6691b3bc)
![7](https://github.com/robodhruv/visualnav-transformer/assets/67970392/272de5a2-8188-4255-81eb-64da79f61570)
![8](https://github.com/robodhruv/visualnav-transformer/assets/67970392/7b071a8a-3940-4c5c-9cfe-7056215ea740)
![image_67185665](https://github.com/robodhruv/visualnav-transformer/assets/67970392/fdc75f7e-1b7a-4cd7-85d3-495f1f2576e9)

**Comment by vedant-banerjee** [comment]
This is one of the topomaps, but i have tried with a few others as well, and issue of finding closest node and goal node is still there, and collisions are happening. @robodhruv

**Comment by robodhruv** [comment]
Thanks for sharing, Vedant! I am quite confident that the issue arises from the camera -- RealSense D435i is a fairly narrow FoV (~90 degrees) and quite OOD from what the model is trained on. I would recommend switching to a wide-angle camera, either to replace the D435i, or just add a second USB camera to your build. While this issue is particularly pronounced with ViNT/NoMaD, in general, I expect fisheye cameras to be more useful because the added FoV helps in short-range collision detection and avoidance.

Here is an example camera that you can use: https://www.amazon.com/ELP-Fisheye-Lightburn-Machine-Embedded/dp/B00LQ854AG/

**Comment by vedant-banerjee** [comment]
Alright thanks for the help, also does the robot size also matter? or this is taken into consideration while fine tuning the model, to avoid collisions @robodhruv

**Comment by robodhruv** [comment]
The robot size does matter, and can get you in trouble if the robot is too large, but I suspect this will not be a big issue for you unless you are trying to work in a very dense indoor environment. We have tested the model on an [AgileX Tracer robot](https://www.trossenrobotics.com/agilex-tracer-agv.aspx) base, which is quite large (50x60 cm) and the model seems to work fine.

**Comment by vedant-banerjee** [comment]
Okay thanks i will change the camera as suggested and see if i get better results

**Comment by robodhruv** [comment]
Good luck and feel free to re-open the issue after you've tried!

**Comment by vedant-banerjee** [comment]
@robodhruv I have tried using a fisheye wide angle lens camera of fov 190 degree, i will share some images of the topomap, i am facing the same issue where the closest_node is not updating correctly as the robot is moving. and hence its losing track. I have not trained/fine tuned it, this is when i run zero shot.
![0](https://github.com/robodhruv/visualnav-transformer/assets/67970392/e1bf0ea2-4f0d-44b7-bd77-fdf977d16c4c)
![1](https://github.com/robodhruv/visualnav-transformer/assets/67970392/f411bf77-cc3d-42dc-b329-0ca3a75a197b)
![2](https://github.com/robodhruv/visualnav-transformer/assets/67970392/55525a69-f58b-4ee3-b2d3-bb66724ac346)
![3](https://github.com/robodhruv/visualnav-transformer/assets/67970392/5e37f245-9115-4c81-b71e-082ff2eb824a)
![4](https://github.com/robodhruv/visualnav-transformer/assets/67970392/3c6df45c-779a-4d16-b775-2802050a0e0c)
![5](https://github.com/robodhruv/visualnav-transformer/assets/67970392/be46754f-6a5c-4f44-b99b-1ec0cf4c3010)
![6](https://github.com/robodhruv/visualnav-transformer/assets/67970392/b4bf2c75-99f8-4c28-824e-3473c590941e)
![7](https://github.com/robodhruv/visualnav-transformer/assets/67970392/ea3c7f75-59f7-439c-b1eb-8cfc352638e8)
![8](https://github.com/robodhruv/visualnav-transformer/assets/67970392/91b135a8-dc89-43cb-8f35-21c62a8f78e3)
![9](https://github.com/robodhruv/visualnav-transformer/assets/67970392/4bc60089-dffb-44f0-a12f-462139c1a90f)
![10](https://github.com/robodhruv/visualnav-transformer/assets/67970392/2e48b3d8-329b-43ff-829e-432fe61cf1d1)

**Comment by ByZ0e** [comment]
hi, I am facing the same problem, especially the collisions! Did you find the solutions?
