### ISSUE TITLE
What do you mean the gc and uc  ？ 

### ISSUE THREAD

**Issue by 942411526** [robodhruv/visualnav-transformer#25]
return {
        'uc_actions': uc_actions,
        'gc_actions': gc_actions,
        'gc_distance': gc_distance,
    }

**Comment by evgeniishch** [comment]
> return { 'uc_actions': uc_actions, 'gc_actions': gc_actions, 'gc_distance': gc_distance, }

It corresponds to "goal-conditioned" and "unconditioned" modes described in the paper. The difference is that in unconditioned mode the goal token is masked so the model generates trajectories for exploration.
