### ISSUE TITLE
Did you undistort the images in Go-Stanford dataset before training ViNT model ?

### ISSUE THREAD

**Issue by han-kyung-min** [robodhruv/visualnav-transformer#26]
Hello,

I have a question about your training/testing dataset. 
It seems that the training dataset contains both rectified (SCAND) and distorted images (Go-Stanford). Did you undistort the images in the Go-Stanford dataset before training your models to standardize the image rectification?

Thanks

**Comment by ajaysridhar0** [comment]
We center-cropped the images from the Go-Stanford dataset to have the same aspect ratio as the other images in the combined dataset.  By including rectified and distorted images in the training set, we expect our policy to generalize to more camera types.
