### ISSUE TITLE
Failed to load image 

### ISSUE THREAD

**Issue by jimpap1** [robodhruv/visualnav-transformer#30]
Why does it fail to load images from RECON dataset? 
![fail](https://github.com/robodhruv/visualnav-transformer/assets/161496320/fc16a57a-580e-4910-bec8-169fdf130bf6)

**Comment by laozheng1** [comment]
Are you in the training phase? Does the code in the later deployment phase run? I've been running this code recently, and I've had some problems.

**Comment by jimpap1** [comment]
Yes it is in the training part.I haven't moved yet to the deployment part as i'm trying to solve the training errors,

**Comment by robodhruv** [comment]
Did you download the data in the appropriate folders first? Maybe there is a small bug in the image paths?

**Comment by ajaysridhar0** [comment]
Let's move our discussion to here: https://github.com/robodhruv/visualnav-transformer/issues/27.
