### ISSUE TITLE
Question about yaw learning

### ISSUE THREAD

**Issue by evgeniishch** [robodhruv/visualnav-transformer#31]
Good afternoon!

I was curious, why did you choose to include yaw change ψ to the intermediate action space in ViNT? Does it bring extra quality compared to just predicting nomalized actions xy? It's interesting that you do not predict angles in nomad. What was the motivation for that? 

Thank you for great papers anyway ^_^

**Comment by ajaysridhar0** [comment]
Glad you enjoyed the papers! We added yaw predictions to ViNT as an extra supervision signal. However, we found no performance difference and removed it for NoMaD.
