### ISSUE TITLE
how to visualize the prediction traj and gt traj in image view with nomad train and eval pipeline?

### ISSUE THREAD

**Issue by yancie-yjr** [robodhruv/visualnav-transformer#33]
how to visualize the prediction traj and gt traj in image view with nomad train and eval pipeline?

**Comment by kjctphr** [comment]
+1

**Comment by robodhruv** [comment]
If you have the exact camera matrix for the datasets, you can use a simple transform for this visualization (example: https://github.com/robodhruv/visualnav-transformer/issues/22). The relevant code for this can be found in https://github.com/robodhruv/visualnav-transformer/blob/main/train/vint_train/visualizing/action_utils.py under the functions `project_points()` and `plot_trajs_and_points_on_image()`.


 Alternatively, you can produce a 2D top-down visualization.
