### ISSUE TITLE
What is the appropriate resolution or camera configuration?

### ISSUE THREAD

**Issue by AnishShr** [robodhruv/visualnav-transformer#34]
I am trying to deploy different models (GNM, ViNT, NoMaD) on [Jackal](https://docs.clearpathrobotics.com/docs/robots/outdoor_robots/jackal/user_manual_jackal) with [this camera](https://www.amazon.de/dp/B07G88VBWX/ref=pe_27091401_487024491_TE_item_image). The camera configuration [file](https://github.com/robodhruv/visualnav-transformer/blob/main/deployment/config/camera_front.yaml) uses 160 X 120 image which looks like this:
![img_160X120](https://github.com/robodhruv/visualnav-transformer/assets/62991158/35b067ba-0289-4c3c-ba9f-0eaff735734f)

While the default camera configuration of the [usb_cam ](http://wiki.ros.org/usb_cam) node uses a 640 x 480 images, which from the same place looks like this:
![img_640X480](https://github.com/robodhruv/visualnav-transformer/assets/62991158/fcabb58d-9eae-4eaa-b4ba-797e3d3284da)

While creating the topological map and getting the images from camera on-policy while testing these models, which images are appropriate to use? The 640 X 480 images, or the 160 X 120 images? The 160 X 120 images look a lot different than what is shown as the image seen by by the robot in this [video](https://youtu.be/zH8LaIapF6w)- the bottom right image or the robot's view image in this [video](https://youtu.be/6kNex5dJ5sQ).

**Comment by robodhruv** [comment]
It appears that your 160x120 resolution image has some aliasing issues. Consider using PIL resize function for best performance.

That should be a high enough resolution for the topological graph and for the policies. All our experiments have used 85x64 or 160x120 dim images and nothing higher was needed.
