### ISSUE TITLE
Go1 deployment details

### ISSUE THREAD

**Issue by hchlhwang** [robodhruv/visualnav-transformer#35]
Thank you for the great work!

Would it be possible to share scripts relevant to deploying the code on the Go1 robot (e.g., robot.yaml, topomap create code)? 

Thank you.

**Comment by ajaysridhar0** [comment]
Hi @hchlhwang,

I think this might be useful: https://github.com/robodhruv/visualnav-transformer/issues/6#issuecomment-1911494770. Also, check out the section for scripts to generate a topomap: https://github.com/robodhruv/visualnav-transformer/issues/6#issuecomment-1911494770.

--Ajay

**Comment by hchlhwang** [comment]
Can you share the go1.yaml params that worked best for go1? Also, can you reshare the link to creating the topomap? I think your link refers to the go1-run script. Thanks!
