### ISSUE TITLE
About Creating Topological Map

### ISSUE THREAD

**Issue by Breezewrf** [robodhruv/visualnav-transformer#42]
Hi,

Thank you for your awesome open-source work, 
I am new to the field of robotic and curious about why creating a Topological Map and record a rosbag you mentioned on deployment. Since the paper said you proposed the method to navigate and expore robot in a unfamiliar scene, which maybe mean without any map, it seems confict with the concept?

**Comment by tukaiwen** [comment]
Hi~ have you known the answer to this question? I have the same question with you but i don't understand yet. Thanks a lot for help
