### ISSUE TITLE
process_data 

### ISSUE THREAD

**Issue by Qiang-Yun** [robodhruv/visualnav-transformer#9]
Hi,
Is it more reasonable to update 'currtime' within the 'if' statement here? Update 'currtime' after storing synchronized data.
Thanks~

https://github.com/robodhruv/visualnav-transformer/blob/bd3dbda18e0ade852bdedda98866bdb3e599ba72/train/vint_train/process_data/process_data_utils.py#L179C4-L179C4

**Comment by ajaysridhar0** [comment]
Hi @Qiang-Yun,

Thanks for catching this! I fixed it here: https://github.com/robodhruv/visualnav-transformer/commit/5b4c8165d10f0c9246e25cb530a026f8924e61cd

--Ajay

**Comment by Qiang-Yun** [comment]
收到了O(∩_∩)O~
